version: '3.7'

services:
  db:
    image: mariadb:10.4
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${COINSENCE_DB}
      MYSQL_USER: ${COINSENCE_DB_USER}
      MYSQL_PASSWORD: ${COINSENCE_DB_PASSWORD}
    expose:
      - "3306"
    volumes:
      - ./data:/var/lib/mysql
  app:
    build: .
    restart: always
    volumes:
      - ./humhub:/var/www/html
      - ./modules:/var/www/modules
    labels:
      - traefik.enable=true
      - traefik.http.routers.app.rule=Host(`coinsence.localhost`)
      - traefik.http.routers.app.entrypoints=web
    depends_on:
      - db
  pma:
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
    labels:
      - traefik.enable=true
      - traefik.http.routers.pma.rule=Host(`pma.coinsence.localhost`)
      - traefik.http.routers.pma.entrypoints=web
    depends_on:
      - db
  traefik:
    container_name: "traefik"
    image: traefik:v2.0
    restart: always
    command:
      - "--log.level=INFO"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - 80:80
    labels:
      - traefik.enable=true
      - traefik.http.routers.traefik.rule=Host(`monitor.coinsence.localhost`)
      - traefik.http.routers.traefik.entrypoints=web
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
